"""
YOLOv8 Training Script for Poker Card Detection

This script trains a YOLOv8 model to detect and classify playing cards
from PokerOK screenshots.

Dataset Structure:
    training/
    └── card_dataset/
        ├── images/
        │   ├── train/
        │   │   ├── img001.jpg
        │   │   └── ...
        │   └── val/
        │       ├── img001.jpg
        │       └── ...
        └── labels/
            ├── train/
            │   ├── img001.txt
            │   └── ...
            └── val/
                ├── img001.txt
                └── ...

Label Format (YOLO):
    Each .txt file contains lines: class_id center_x center_y width height
    All values normalized to 0-1
    
    Example: 0 0.5 0.5 0.1 0.15
    (Class 0, centered at 50% x/y, 10% width, 15% height)

Classes (52 cards):
    0-12: Clubs (2c, 3c, ..., Ac)
    13-25: Diamonds (2d, 3d, ..., Ad)
    26-38: Hearts (2h, 3h, ..., Ah)
    39-51: Spades (2s, 3s, ..., As)
"""

import os
import sys
from pathlib import Path


# Card classes
RANKS = ['2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K', 'A']
SUITS = ['c', 'd', 'h', 's']

# Generate class names
CLASS_NAMES = [f"{r}{s}" for s in SUITS for r in RANKS]
NUM_CLASSES = len(CLASS_NAMES)  # 52


def create_dataset_yaml(dataset_path: Path, output_path: Path) -> Path:
    """Create YOLO dataset configuration file."""
    yaml_content = f"""# Poker Cards Dataset
# Generated by train_cards.py

path: {dataset_path.absolute()}
train: images/train
val: images/val

# Classes (52 playing cards)
nc: {NUM_CLASSES}
names: {CLASS_NAMES}
"""
    
    yaml_path = output_path / "cards_dataset.yaml"
    yaml_path.write_text(yaml_content)
    print(f"Created dataset config: {yaml_path}")
    return yaml_path


def train_model(
    dataset_yaml: Path,
    epochs: int = 100,
    batch_size: int = 16,
    img_size: int = 640,
    model_size: str = "n",  # n, s, m, l, x
):
    """Train YOLOv8 model for card detection."""
    try:
        from ultralytics import YOLO
    except ImportError:
        print("Error: ultralytics not installed. Run: pip install ultralytics")
        sys.exit(1)
    
    # Load pretrained model
    model_name = f"yolov8{model_size}.pt"
    print(f"Loading base model: {model_name}")
    model = YOLO(model_name)
    
    # Train
    print(f"Starting training for {epochs} epochs...")
    results = model.train(
        data=str(dataset_yaml),
        epochs=epochs,
        batch=batch_size,
        imgsz=img_size,
        project="runs/cards",
        name="train",
        patience=20,
        save=True,
        plots=True,
        device="cpu",  # Use "0" for GPU if available
    )
    
    print(f"Training complete!")
    print(f"Best model saved to: {results.save_dir}/weights/best.pt")
    
    return results


def validate_dataset(dataset_path: Path):
    """Validate dataset structure and contents."""
    print("Validating dataset structure...")
    
    required_dirs = [
        "images/train",
        "images/val",
        "labels/train",
        "labels/val",
    ]
    
    for dir_path in required_dirs:
        full_path = dataset_path / dir_path
        if not full_path.exists():
            print(f"  ❌ Missing: {dir_path}")
            return False
        
        files = list(full_path.iterdir())
        print(f"  ✓ {dir_path}: {len(files)} files")
    
    # Check that images have corresponding labels
    train_images = list((dataset_path / "images/train").glob("*.*"))
    train_labels = list((dataset_path / "labels/train").glob("*.txt"))
    
    print(f"\n  Train: {len(train_images)} images, {len(train_labels)} labels")
    
    val_images = list((dataset_path / "images/val").glob("*.*"))
    val_labels = list((dataset_path / "labels/val").glob("*.txt"))
    
    print(f"  Val: {len(val_images)} images, {len(val_labels)} labels")
    
    if len(train_images) == 0:
        print("\n  ⚠️ No training images found!")
        print("  Add card images to training/card_dataset/images/train/")
        return False
    
    return True


def create_sample_dataset(dataset_path: Path):
    """Create sample dataset structure with placeholder files."""
    print("Creating sample dataset structure...")
    
    dirs = [
        "images/train",
        "images/val",
        "labels/train",
        "labels/val",
    ]
    
    for dir_path in dirs:
        (dataset_path / dir_path).mkdir(parents=True, exist_ok=True)
    
    # Create README with instructions
    readme = """# Card Dataset

## How to Create Training Data

1. Take screenshots of PokerOK tables during play
2. Use a labeling tool like:
   - LabelImg (https://github.com/heartexlabs/labelImg)
   - Roboflow (https://roboflow.com/)
   - CVAT (https://cvat.org/)

3. Label each card with its class:
   - 2c, 3c, ..., Ac (clubs)
   - 2d, 3d, ..., Ad (diamonds)
   - 2h, 3h, ..., Ah (hearts)
   - 2s, 3s, ..., As (spades)

4. Export in YOLO format

## Class IDs

| ID | Card | ID | Card | ID | Card | ID | Card |
|----|------|----|----- |----|------|----|------|
| 0  | 2c   | 13 | 2d   | 26 | 2h   | 39 | 2s   |
| 1  | 3c   | 14 | 3d   | 27 | 3h   | 40 | 3s   |
| 2  | 4c   | 15 | 4d   | 28 | 4h   | 41 | 4s   |
| 3  | 5c   | 16 | 5d   | 29 | 5h   | 42 | 5s   |
| 4  | 6c   | 17 | 6d   | 30 | 6h   | 43 | 6s   |
| 5  | 7c   | 18 | 7d   | 31 | 7h   | 44 | 7s   |
| 6  | 8c   | 19 | 8d   | 32 | 8h   | 45 | 8s   |
| 7  | 9c   | 20 | 9d   | 33 | 9h   | 46 | 9s   |
| 8  | Tc   | 21 | Td   | 34 | Th   | 47 | Ts   |
| 9  | Jc   | 22 | Jd   | 35 | Jh   | 48 | Js   |
| 10 | Qc   | 23 | Qd   | 36 | Qh   | 49 | Qs   |
| 11 | Kc   | 24 | Kd   | 37 | Kh   | 50 | Ks   |
| 12 | Ac   | 25 | Ad   | 38 | Ah   | 51 | As   |

## Recommended Dataset Size

- Minimum: 50-100 images per card (2600-5200 total)
- Recommended: 200-500 images per card
- Include variety: different table themes, lighting, positions

## Tips

1. Capture cards at different sizes and positions
2. Include partially obscured cards
3. Balance the dataset across all 52 classes
4. Split 80/20 for train/val
"""
    
    (dataset_path / "README.md").write_text(readme)
    print(f"Created dataset structure at: {dataset_path}")
    print("See README.md for labeling instructions")


def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="Train YOLOv8 for poker card detection")
    parser.add_argument("--dataset", type=str, default="card_dataset",
                       help="Path to dataset directory")
    parser.add_argument("--epochs", type=int, default=100,
                       help="Number of training epochs")
    parser.add_argument("--batch", type=int, default=16,
                       help="Batch size")
    parser.add_argument("--img-size", type=int, default=640,
                       help="Image size for training")
    parser.add_argument("--model", type=str, default="n",
                       choices=["n", "s", "m", "l", "x"],
                       help="YOLOv8 model size")
    parser.add_argument("--validate-only", action="store_true",
                       help="Only validate dataset, don't train")
    parser.add_argument("--create-sample", action="store_true",
                       help="Create sample dataset structure")
    
    args = parser.parse_args()
    
    # Get paths
    script_dir = Path(__file__).parent
    dataset_path = script_dir / args.dataset
    
    # Create sample dataset if requested
    if args.create_sample:
        create_sample_dataset(dataset_path)
        return
    
    # Validate dataset
    if not dataset_path.exists():
        print(f"Dataset not found at: {dataset_path}")
        print("Run with --create-sample to create the structure")
        return
    
    if not validate_dataset(dataset_path):
        print("\nDataset validation failed!")
        return
    
    if args.validate_only:
        print("\nDataset validation passed!")
        return
    
    # Create dataset YAML
    yaml_path = create_dataset_yaml(dataset_path, script_dir)
    
    # Train
    train_model(
        dataset_yaml=yaml_path,
        epochs=args.epochs,
        batch_size=args.batch,
        img_size=args.img_size,
        model_size=args.model,
    )


if __name__ == "__main__":
    main()
